# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historical_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('open', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vol', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=5)),
            ],
        ),
    ]
